language: python
python:
  - "2.6"
  - "2.7"

before_script:
  - '[ "${TRAVIS_PYTHON_VERSION}" = "2.6" ] && pip install --use-mirrors unittest2 || /bin/true'
  
script: python setup.py test
build_image: shippable/minv2
